FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY pyproject.toml README.md ./
COPY openrestor ./openrestor
COPY configs ./configs
COPY schemas ./schemas
RUN python -m pip install --no-cache-dir .

ENTRYPOINT ["python", "-m"]
